version: '3.9'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest-lite
    container_name: oracle-free-lite-mehul
    ports:
      - "1521:1521"   # Oracle DB port
    environment:
      - ORACLE_PWD=YourPassword123   # Set your SYS/SYSTEM password
    volumes:
      - oracle-data:/opt/oracle/oradata  # Persist data

volumes:
  oracle-data:
    driver: local

